
# SEO settings
title: "Additional Memory"
title2: "" # default: ""
description: "Notes about technology and software development."
keywords: "software development technology"
# TODO: Change when configured with the real domain
url: http://maeserucgar.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# TODO: Configure with my own analytics and disqus accounts
google_analytics: UA-XXXXX-XX
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "hnbloggithub"
twitter_username: "Maese_Richar"
comments: false

# Build settings
permalink   : /:year/:month/:day/:title
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Additional Memory"
  job      : "virtual note book"
  bio      : "."
  thumb    : /images/author.jpg
  email    : rodriguezfernandezricardo@gmail.com
  url      : http://maeserichar.github.io
  github   : http://github.com/maeserichar

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
